### ISSUE TITLE
 Hello, can you provide a test code and pre-training model?

### ISSUE THREAD

**Issue by 17853313621** [julilien/PLDepth#2]
Hello, can you provide a test code and pre-training model?

**Comment by julilien** [comment]
The evaluation code can be found in the respective branch: https://github.com/julilien/PLDepth/tree/eval
We provide the link to a pretrained EfficientNet-based model in the README: https://drive.google.com/file/d/13I80Luz-xLrhQ9KewecTIWfo5_AQaXF7
