### ISSUE TITLE
Questions regarding evaluation

### ISSUE THREAD

**Issue by jwyndreee** [julilien/PLDepth#3]
Dear author,

Thank you for your great work.

I have some questions regarding the procedure for evaluating the ordinal error in your paper.

Did you first random sample 50k pairs of points, filter equidistant points, and then measure the ordinal error on the remaining points?

Or, did you random sample 50k pairs of points that are not equidistant and then measure its error?

Thanks,

**Comment by julilien** [comment]
Hi, thanks for your interest!

For the evaluation, we did not filter out any point pair from the 50k random samples. As written in Section 4.3 of the paper, pairs with the exact same depth have a relation of 0, which is also covered by the ordinal error metric definition, but, however, almost never occurs in the data as we do not quantize the depth maps before.

**Comment by jwyndreee** [comment]
Thank you for your quick answer. And also thank you for the updates on the evaluation code, which will greatly help me out!

I have some further questions regarding the evaluation procedure. As far as I know, Ibims and DIODE datasets have their own masks for filtering pixels with valid depth. Have you used them during your evaluation? I could not find them in the current code version.

Thanks,

**Comment by julilien** [comment]
You can find the evaluation code in the respective branch: https://github.com/julilien/PLDepth/blob/eval

Unfortunately, we did not use these masks for iBims-1 and DIODE, only for HR-WSI (which also provides depth consistency masks; we used them for training and evaluation). What we did was assigning the depth capacity of 350 to zero values in DIODE (which reflect depths far off; see https://github.com/julilien/PLDepth/blob/8cb385e595053abc6762c536b2d807d7df784dbd/pldepth/eval/test_suite.py#L46). That being said, I would recommend to use the masks, which would result in less noisy results, but I wouldn't expect the relative order of performances changing too much (as all evaluated methods suffer from potentially distorted depths). The performances should get a bit better with the masks.

**Comment by jwyndreee** [comment]
Thank you. One quick last question, is the performance gap big between a model that is trained on the sampling strategy of Sec 3.5(decreasing order of sum of depth difference) and random-only sampling, with all other factors controlled? (e.g. number of points, architecture)

**Comment by julilien** [comment]
It depends on the number of total sampled rankings R per image. If R is small, the chances to observe only a few particularly "informative" rankings in random-only sampling is relatively high. As we sample N*R rankings per image with N > 1 (in our experiments N=5), we get a significantly higher chance to observe particularly informative rankings as we see way more of them. In our experiments, we used R=100 to get the results as shown in Tables 2 and 3, there was a quite notable performance gap, so I would suggest you to stick to our advanced sampling strategy.

**Comment by jwyndreee** [comment]
Thanks!
